name: Get metrics
on:
  # Run on manual trigger
  workflow_dispatch:

  # Run when pushing to main or dev branches
  push:
    branches:
      - main
      - dev*

jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl --request GET \
          --url "https://api.github.com/adversarial-robustness-toolbox" \
          --header "Authorization: Bearer $GH_TOKEN"