name: Get metrics
on:
  # Run on manual trigger
  workflow_dispatch:

  # Run when pushing to main or dev branches
  push:
    branches:
      - main
      - dev*

jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl --request GET \
          --url "https://api.github.com/search/issues?q=AutoAttack+in%3Atitle+is%3Apull-request+repo%3ATrusted-AI%2Fadversarial-robustness-toolbox" \
          --header "Accept: application/vnd.github+json" \
          --header "Authorization: Bearer $GH_TOKEN"